### ISSUE TITLE
Measure Tools: MeasureToolsUiItemsProvider hardcodes StageUsage.General

### ISSUE THREAD

**Issue by adrianclinansmith** [iTwin/viewer-components-react#1019]
I want to add [MeasureToolsUiItemsProvider](https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/measure-tools/src/ui-2.0/MeasureToolsUiProvider.tsx) to a frontstage. Unfortunately, the frontstage has StageUsage.Edit, but your Provider only accepts StageUsage.General, which is hardcoded:

```ts
public provideToolbarItems(
    _stageId: string,
    stageUsage: string,
    toolbarUsage: ToolbarUsage,
    toolbarOrientation: ToolbarOrientation,
  ): ToolbarItem[] {
    if (stageUsage === StageUsage.General && toolbarUsage === ToolbarUsage.ContentManipulation) {
    ...
```

Could the Provider accept Edit and possibly other staging usages as well? 

I could make a PR to add more usages, unless there's a reason why it should only be General.

**Comment by aruniverse** [comment]
How are you guys using `StageUsage.Edit` ? Feel free to open a PR to add support for your Stage or a more generic solution
