### ISSUE TITLE
Tree widget: On startup CategoriesTree executes the same query twice

### ISSUE THREAD

**Issue by grigasp** [iTwin/viewer-components-react#1037]
1. Open test viewer
2. Open dev tools to track network requests
3. Switch to Categories tree
4. Notice there are 3 network requests, 2 of them execute the exact same query:
   ```sql
   SELECT ECInstanceId as id FROM BisCore.SpatialCategory WHERE ECInstanceId IN (SELECT DISTINCT Category.Id as id from BisCore.GeometricElement3d WHERE Category.Id IN (SELECT ECInstanceId from BisCore.SpatialCategory))
   ```

**Comment by saskliutas** [comment]
This is expected in `React.StrictMode` as `useEffect`s are invoked twice. It run query once without `StrictMode`
