### ISSUE TITLE
The e2e tests for viewer-components-react are timing out

### ISSUE THREAD

**Issue by tejassutar2024** [iTwin/viewer-components-react#1048]
For some reason, e2e tests for viewer-components-react get cancelled. It looks like there is timeout after 60 min.
https://github.com/iTwin/viewer-components-react/pull/1042/checks?check_run_id=30186426650
This restricts pull request from getting merged.

**Comment by grigasp** [comment]
@tejassutar2024, it looks like the job doesn't hand and is just taking too long... E.g. the first run managed to complete all but 2 tests until it hit the timeout... For the time being I just increased the timeout: https://github.com/iTwin/viewer-components-react/pull/1049. Will look into how to improve the job performance a bit later.
