### ISSUE TITLE
[Tree Widget] model / category selection inconsistencies with selection based tools

### ISSUE THREAD

**Issue by jason-crow** [iTwin/viewer-components-react#1099]
- the model tree in @itwin/tree-widget-react@3.x supports clicking on model / category nodes to select their related elements
- these selection events do not propagate to the imodel.selectionSet, unlike selection events from graphical elements
- due to this difference with how these model / category selection events are handled compared to graphical elements, there are some inconsistencies with selection based tools:
   - the appui's SyncUiEventId.SelectionSetChanged event only raised from imodel.selectionSet.onChange events
   - tools that synchronize with SyncUiEventId.SelectionSetChanged, such as clear selection tools and visibility tools, do not respond to these selections
   - furthermore, many of these tools that sync with SyncUiEventId.SelectionSetChanged use the imodel.selectionSet for their respective tool's action. (i.e. the clear selection tool when activated will clear all the selection from imodel.selectionSet)
   - consequently, tools that should respond to selection events fail to do so and even if they did they would fail to work correctly

**Comment by grigasp** [comment]
Thanks for reporting this. 

I started some discussions with the team responsible for Tools which use the `SelectionSet`. Depending on the outcome, we may need to temporarily add an option to disable selection of certain nodes, like we had in 2.x widget, until we can properly support selecting Models and Categories. Will update on this shortly.

**Comment by grigasp** [comment]
@jason-crow, I have a couple of PRs that will fix this, but they're only going to be available with `5.0` release of `itwinjs-core`. Can you wait for that or would you like the option in tree widget to disable selection of specific nodes, as a short-term solution?

**Comment by jason-crow** [comment]
> [@jason-crow](https://github.com/jason-crow), I have a couple of PRs that will fix this, but they're only going to be available with `5.0` release of `itwinjs-core`. Can you wait for that or would you like the option in tree widget to disable selection of specific nodes, as a short-term solution?

We would consider this a requirement for enabling the tree widget v3, so it would be nice to have that enabled before itwinjs v5

@vermanas  @jjbeckman13

**Comment by grigasp** [comment]
@jason-crow, the feature has just been released with the [@itwin/tree-widget-react @ 3.2](https://www.npmjs.com/package/@itwin/tree-widget-react/v/3.2.0) version. You can find implementation example in [the PR](https://github.com/iTwin/viewer-components-react/pull/1124#issue-2745229059) or in [our test viewer](https://github.com/iTwin/viewer-components-react/blob/3f339ca54c79ac50071d45f9ae3af1ed516cb40d/apps/test-viewer/src/UiProvidersConfig.tsx#L126C24-L126C106).

I'll leave this issue open until you confirm this solves your problem - please let me know how it goes.

**Comment by jason-crow** [comment]
> [@jason-crow](https://github.com/jason-crow), the feature has just been released with the [@itwin/tree-widget-react @ 3.2](https://www.npmjs.com/package/@itwin/tree-widget-react/v/3.2.0) version. You can find implementation example in [the PR](https://github.com/iTwin/viewer-components-react/pull/1124#issue-2745229059) or in [our test viewer](https://github.com/iTwin/viewer-components-react/blob/3f339ca54c79ac50071d45f9ae3af1ed516cb40d/apps/test-viewer/src/UiProvidersConfig.tsx#L126C24-L126C106).
> 
> I'll leave this issue open until you confirm this solves your problem - please let me know how it goes.

@grigasp thanks for the heads up, ill pull this in and report back

**Comment by jason-crow** [comment]
@grigasp can confirm this resolves our issue. thanks!
