### ISSUE TITLE
Large number of `queryRows` requests when emphasizing or opening another viewport

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/viewer-components-react#1101]
Hi,
    since we upgraded to tree-widget-react ^3.0, we've noticed some performance hits when using our civil tools. After digging a little, we found that when elements are emphasized as part of our tool workflow, there is a large number of `IModelReadRpcInterface-3.7.0-queryRows` requests being performed. It also happens on an even larger scale when we open our section viewport.

It ultimately stabilizes as we keep playing with the tools and the views (most likely due to caching), but we have had a few complaints of performance degradation already, and even in localhost there is a noticeable performance hit from whatever was done in tree-widget-react: 2.x.

I have attached a video that shows the number of requests after a cold start of the page.
The first part when I open the `2-point cross-section` tool is to validate that if no emphasizing is involved, there are no `queryRows` requests being made.
At 0:30, the `Perpendicular cross section` tool is started, which will emphasize all alignments in the model.
At 0:45, we open the secondary viewport which triggers its own list of requests.

Please reach out if you need more info.
Thanks,
Alex

Attached video:
https://github.com/user-attachments/assets/518c24fa-c55f-4501-8678-9c975190fdda

**Comment by grigasp** [comment]
@a-gagnon, the fix has been released with `@itwin/tree-widget-react` version `3.1.0`. Please let us know if the problem you were seeing is gone, I'll keep this issue open until your confirmation.

**Comment by grigasp** [comment]
2 weeks passed without any feedback, closing the issue as resolved. Please re-open or create a new one if you're still seeing any problems.
