### ISSUE TITLE
Repository move announcement

### ISSUE THREAD

**Issue by skirby1996** [iTwin/viewer-components-react#144]
On Monday, October 4th, the viewer-components-react repo will be transferred to the [iTwin Platform](https://github.com/iTwin) organization on Github.

All branches, pull requests, issues, and discussions will be transferred along with the repository, and all links to the old repository will redirect to the new repository which will be found at https://github.com/iTwin/viewer-components-react.

Once the move is complete, we recommend that you update the git origin in your local copy of the repo to the new repository location using:

`git remote set-url origin https://github.com/iTwin/viewer-components-react.git`

**Comment by skirby1996** [comment]
The viewer-components-react repo has been successfully transferred to the iTwin Platform organization. Please use this thread if you experience any issues related to the transfer.

**Comment by MichaelBelousov** [comment]
@skirby1996 I seem to have lost the ability to push a new branch to this repo

**Comment by calebmshafer** [comment]
going to close this out. If anyone has issues, please just leave a comment.
