### ISSUE TITLE
iTwin.js 3.0 Support

### ISSUE THREAD

**Issue by calebmshafer** [iTwin/viewer-components-react#161]
With the upcoming iTwin.js Core 3.0 release, the packages within this repository will need to be updated.

The following list of packages are still active in this repository and need to be updated. In addition some notes on how the release of these packages will happen is defined below (feedback is definitely appreciated).

## List of packages

If anyone has a PR for updating, please link them to this issue to keep track.

- [x] @bentley/tree-widget-react
- [x] @bentley/property-grid-react
- [x] @bentley/imodel-content-tree-react
- [x] @bentley/imodel-react-hooks
- [x] @bentley/geo-tools-react
- [x] @bentley/measure-tools-react
- [x] @bentley/breakdown-trees-react

## Release strategy

The new version of the packages will live along side the currently supported 2.x packages in the repository to avoid having to create a separate release branch if a fix is required.

All packages released for the 3.0 release are transitioning to use the `@itwin` scope instead of the currently used `@bentley`. With the transition to the new scope/name we will be resetting all versions back down to 0.x.0 for the initial releases. Once they are deemed stable on top of iTwin.js Core 3.0 they will be released as a new major version 1.0.

(Side Note: The iTwin Viewer depends on the `@bentley/property-grid-react` and `@bentley/tree-widget-react` so those will be a requirement for the 3.0 release of both iTwin.js Core and the iTwin Viewer).

**Comment by aruniverse** [comment]
All of the previous 2.x packages have been upgraded to 3.0
