### ISSUE TITLE
Grouping & Mapping Widget 'Groub By' check box issue

### ISSUE THREAD

**Issue by StuartKeelingWSP** [iTwin/viewer-components-react#208]
<img width="1593" alt="itwin Viewer" src="https://user-images.githubusercontent.com/100842723/158164955-bbba2a1b-b94a-48f1-a4da-19217c083d41.PNG">

Hi there, I have set up the grouping and mapping widget, however out of the box the check boxes seem to not be working as they should. They are so small and skinny that I cant tell if anything is checked/selected or not. see image provided for evidence. Thanks in advance for you time

**Comment by Guillar1** [comment]
Hey Stuart, 

We just published a new version that contains a fix for this. Let me know if it works out for you.
