### ISSUE TITLE
Tree Widget: Test coverage

### ISSUE THREAD

**Issue by grigasp** [iTwin/viewer-components-react#376]
This is sad:
![Image](https://user-images.githubusercontent.com/35135765/229698041-32caf0ab-45ed-4909-a5ee-cc9a566d1892.png)

I hope for the 1.0 release we could at least get to 80%

**Comment by grigasp** [comment]
@saskliutas @simasjar, I'll add tests for imodel content tree.

**Comment by grigasp** [comment]
Results after completing https://github.com/iTwin/viewer-components-react/pull/451:
![image](https://user-images.githubusercontent.com/35135765/234858695-d8021563-934d-4679-a740-e62bb6e9e078.png)

**Comment by saskliutas** [comment]
I am working on tests for `TreeHeader` and `SearchBox`

**Comment by saskliutas** [comment]
Working on tests for:
[TreeFilteringState.ts](https://github.com/iTwin/viewer-components-react/issues/TreeFilteringState.ts.html)
[TreeWidgetComponent.tsx](https://github.com/iTwin/viewer-components-react/issues/TreeWidgetComponent.tsx.html)
[TreeWidgetUiItemsProvider.tsx](https://github.com/iTwin/viewer-components-react/issues/TreeWidgetUiItemsProvider.tsx.html)

**Comment by saskliutas** [comment]
Results after completing https://github.com/iTwin/viewer-components-react/pull/469
![image](https://github.com/iTwin/viewer-components-react/assets/24278440/91429d80-fb6b-4278-ba3f-4dccfbbc5395)

**Comment by grigasp** [comment]
Results after completing https://github.com/iTwin/viewer-components-react/pull/477
![image](https://github.com/iTwin/viewer-components-react/assets/35135765/5decb5c9-c66d-4dc0-8a44-32c78ba30246)
