### ISSUE TITLE
@itwin/grouping-mapping-widget: Support iTwin.js and AppUI 4.0

### ISSUE THREAD

**Issue by calebmshafer** [iTwin/viewer-components-react#408]

**Comment by aruniverse** [comment]
@arnobmallickbsw any update on getting gm updated?

**Comment by Guillar1** [comment]
Hey @aruniverse, we are figuring out a timeline for this.

**Comment by aruniverse** [comment]
as per @arnobmallickbsw this pkgs is only for "Reference", therefore it will not be required for DR to upgrade.
