### ISSUE TITLE
Models tree buttons expand vertically  after . Previously it was expanding Horizontally.

### ISSUE THREAD

**Issue by muthubentley** [iTwin/viewer-components-react#410]
Before 0.7.0 when the searchbar is clicked in Models tree, "..." will be displayed. When clicking the "..." button, Toolbar will expand horizontally , Refer to the below screenshot
![image](https://user-images.githubusercontent.com/107229931/228451474-3afdc908-968c-4203-9540-d0c06a8af7d6.png)
After 0.7.0 when "..." is clicked, Toolbar is explanding vertically.
![image](https://user-images.githubusercontent.com/107229931/228451736-795a6d2f-5809-4965-bb75-81af29a3d89d.png)

Partner would want it to be expanding horizontally . Is it possible?

**Comment by grigasp** [comment]
@muthubentley, this approach was intentionally chosen to avoid the horizontal toolbar not fitting in cases when the tree component is not wide enough. Is vertical alignment really a big problem here?

**Comment by muthubentley** [comment]
@grigasp I will check with user and come back

**Comment by muthubentley** [comment]
@grigasp  User though it was a defect, if it is a intentional change, User is ok with this . we can close this.
