### ISSUE TITLE
iModel react hooks: Update dependencies to 4.0

### ISSUE THREAD

**Issue by calebmshafer** [iTwin/viewer-components-react#419]

**Comment by aruniverse** [comment]
@jason-crow @jjbeckman13 is this pkg still being used?
was this just for the it1 markers which arent required in the new workflow?

**Comment by anthony-barletta** [comment]
Watersight is using this package and we're looking to upgrade to 4.0 soon

**Comment by aruniverse** [comment]
0.2.0 should support this ver
https://github.com/iTwin/viewer-components-react/pull/661
