### ISSUE TITLE
In Models tree, tooltip of eye icon shows the localization key rather than value

### ISSUE THREAD

**Issue by muthubentley** [iTwin/viewer-components-react#423]
In Models tree, tooltip of eye icon shows the localization key rather than value. Refer to the below screenshot
![image](https://user-images.githubusercontent.com/107229931/231331356-d3ac05dc-c750-40b1-b789-4515d389ba10.png)

This behavior is observed in tree-widget-react 0.7.2 version, not sure about the previous versions.
Issue can be reproduced in below sandbox:
https://www.itwinjs.org/sandboxes/MuthuKalamani/ModelTreeWidgetCustomizations

Since the partner from Japan is using this and would like to show the text in Japanese, Request to fix it earlier

**Comment by saskliutas** [comment]
I couldn't reproduce this issue locally. I have looked into sandbox and it looks like sandbox is using localization file from older `tree-widget-react` version as it has it's own copy of `tree-widget-react` localization file which is now out of date. Make sure that the app uses localization file from `tree-widget-react` package.

Is the app facing this issue built using `@bentley/react-scripts`? 
Can you verify that `build` folder contains `TreeWidget.json` file in `locales` folder after running `react-scripts build` (`npm run build` if app was build using cra-template)?
If `TreeWidget.json` exists can you verify if there are any network errors related to `TreeWidget.json` when starting app?

**Comment by muthubentley** [comment]
@saskliutas 
Thanks for the confirmation. I found the issue, It is the problem of latest version of @bentley/react-scripts
When user used @bentley/react-scripts 4.0.5 version, the Treewidget.json contains all elements. Refer below
![image](https://user-images.githubusercontent.com/107229931/231779456-d625ce87-a3e2-43c7-b86c-1e412033a0b3.png)
But When user uses the latest  @bentley/react-scripts 5.0.4 version, the Treewidget.json is does not contain all elements. ONly the first half is available.
![image](https://user-images.githubusercontent.com/107229931/231779769-89968163-0b48-4105-8f43-34ff4da671e3.png)

Can you please confirm what is the issue with @bentley/react-scripts 5.0.4 version or route this issue to the corresponding team.

**Comment by aruniverse** [comment]
@muthubentley can you take a look at: https://github.com/iTwin/viewer/issues/256#issuecomment-1507016666
And see if this helps resolve the issue?

**Comment by muthubentley** [comment]
@aruniverse 
After setting the usenpm envvar to true, en version gives the correct Treewidget.json whereas the ja version is still the shorter one.

**Comment by saskliutas** [comment]
@muthubentley Where is `ja` version coming from? Is it generated during build or is it stored somewhere? Maybe it was generated using older `tree-widget-react` version and was never updated?

**Comment by muthubentley** [comment]
@saskliutas 
I will give details on how Fukui handles localization. In their project folder they have a public folder under which they store the localization json file for en and ja language. Refer to below
![image](https://user-images.githubusercontent.com/107229931/232664497-75e3caf2-b993-46bc-9236-aeb00df72baa.png)

Fukui had TreeWidget.json from the beginning but it was having only the below keys:
![image](https://user-images.githubusercontent.com/107229931/232664630-cbe21f1a-a488-4032-bcf8-60b50332957a.png)

But they could still able to display the tooltips of Models tree in Japanese. I was not sure how it was possible, when asked Fukui said they had the localization text for tooltips are defined in UiFramework.json.
![image](https://user-images.githubusercontent.com/107229931/232664827-49fd5e9f-ca46-49b4-a8e8-125b91fdae06.png)

The initial problem is once they updated to latest tree-widget-react packages, they could not see the text and only keys were visible. Since you said TreeWidget.json was not updated , I updated them to the format you gave in both "ja"and "en" folders. In en mode the text gets displayed properly but in ja mode , only the English text is visible instead of Japanese text.

Now Fukui has two questions:
1)Initially localization for Models tree came from UiFramework.json. Is it changed to TreeWidget.json in latest versions?
2)What should be done to show the japanese texts in Models tree. I updated the TreeWidget.json in ja folder as well but only english text is displayed. Does this has anything to do with cache? Please advice.

**Comment by muthubentley** [comment]
@saskliutas  Thanks for the explanation. Understood about 1.
Regarding 2, I use a TreeWidget.json with same keys in en and jp folder. Please find the files below. 
[build.zip](https://github.com/iTwin/viewer-components-react/files/11259459/build.zip)

Still I dont get the Japanese displayed, Is there anything wrong with these files?

**Comment by saskliutas** [comment]
I tested ja `TreeWidget.json` file from the zip you provided and it worked in viewer app for me. Make sure to change language to Japanese. I added this code to `onIModelAppInit` callback for testing: `await IModelApp.localization.changeLanguage("ja");`

![image](https://user-images.githubusercontent.com/24278440/232736211-f1b94550-4370-48ad-860b-f25fff4ba5d4.png)

**Comment by muthubentley** [comment]
@saskliutas Thanks I got the Japanese text appearing now. the problem was setting the locale.
After setting this "await IModelApp.localization.changeLanguage("ja");" I got it worked.
