### ISSUE TITLE
NPM fails to resolve dependency tree for @itwin/measure-tools-react@0.11.0

### ISSUE THREAD

**Issue by linasburneika** [iTwin/viewer-components-react#465]
Steps to reproduce

1. create a new package.json as follows
```
{
  "name": "measure",
  "version": "1.0.0",
  "dependencies": {
    "@itwin/measure-tools-react": "^0.11.0"
  }
}
```
2. run `npm install`. I'm using npm version 8.1.4, which is bundled with node 18 LTS
3. NPM throws error: ERESOLVE unable to resolve dependency tree

Previous version 0.10.6 of @itwin/measure-tools-react didn't have this problem (however it was showing a bunch of peer dependency conflicts as warnings)

**Comment by aruniverse** [comment]
@linasburneika is this still an issue?

**Comment by linasburneika** [comment]
Yes, it's still a problem (tested with npm v10.2.5), but I don't understand why it fails. Npm is installing peer dependencies automatically, but due to some reason it picks react-dom@18.2.0 in this case, but it should backtrack to v17 because there is no constraint in the dep tree demanding specifically v18. It seems like a bug in npm itself. 

pnpm resolves entire dep tree properly without any warning.

I figured out it's necessary to explicitly specify react and react-dom in the project, then npm resolves it properly without any warning too (even with strict peers check enabled):
```
{
    "name": "measure",
    "version": "1.0.0",
    "dependencies": {
      "@itwin/measure-tools-react": "^0.14.2",
      "react": "^17.0.0",
      "react-dom": "^17.0.0"
    }
  }
```

I think you can close it, there is nothing you can do about it.
