### ISSUE TITLE
[imodel-select-react] loads forever if you've never loaded an iModel in design review before

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/viewer-components-react#50]
Determined with @wilmaier that until an iModel cache is created (i.e. by opening an iModel in design review), the prompt will remain forever "fetching project info". I'm not personally aware of the cache or implementation, but was having issues using this package until Wil recommended me to try loading an iModel in design review first (which I did in a different browser), after which it started loading immediately.

**Comment by aruniverse** [comment]
For which package? I assume imodel-select-react?

**Comment by MichaelBelousov** [comment]
Yes

**Comment by aruniverse** [comment]
closing this issue as this pkg has been deprecated
