### ISSUE TITLE
@itwin/grouping-mapping-widget has dependency on @itwin/itwinui-css

### ISSUE THREAD

**Issue by linasburneika** [iTwin/viewer-components-react#518]
@itwin/grouping-mapping-widget imports sass files from @itwin/itwinui-css, but this dependency is not specified in "dependencies" or "peerDependencies" of package.json.

If you use strict dependencies (e.g. pnpm), then the build fails, unless @itwin/itwinui-css is explicitly added to the project.

**Comment by Guillar1** [comment]
Hello, 
We are following the recommended [guidelines](https://github.com/iTwin/iTwinUI-react/wiki/version-conflicts#for-librarypackage-authors) for using iTwin UI in libraries. @itwin/itwinui-css is a transient dependency through itwin/itwinui-react. I am having trouble reproducing this failure on pnpm v8.4. I do not have @itwin/itwinui-css listed as a dependency nor @itwin/itwinui-react on the parent app.
Lockfile is generating correctly a single instance of itwinui-react.
![image](https://github.com/iTwin/viewer-components-react/assets/26608199/294391cb-9621-438c-8815-4ff2f3438170)
![image](https://github.com/iTwin/viewer-components-react/assets/26608199/f98b850f-a25e-4921-96a0-ab876b34c4a0)

FYI, this is on version 0.6.1 of the widget. The last version package version that is on iTwinUI 1.x. The most recent version does not include any imports as it takes advantage of CSS variables.
