### ISSUE TITLE
Tree Widget: Add support for react 18

### ISSUE THREAD

**Issue by saskliutas** [iTwin/viewer-components-react#672]
Tree widget does not work with react 18 in `StrictMode` due to double rendering.

**Comment by muthubentley** [comment]
@saskliutas All the below packages doesnt have react 18 as their peer dependency. 
1. @itwin/breakdown-trees-react
2. @itwin/measure-tools-react
3. @itwin/property-grid-react
4. @itwin/tree-widget-react

All of them belongs to this repo. Will you be able to fix all of them with this issue or do you need a separate issue for fixing each package?

**Comment by grigasp** [comment]
> @saskliutas All the below packages doesnt have react 18 as their peer dependency.
> 
> 1. @itwin/breakdown-trees-react
> 2. @itwin/measure-tools-react
> 3. @itwin/property-grid-react
> 4. @itwin/tree-widget-react
> 
> All of them belongs to this repo. Will you be able to fix all of them with this issue or do you need a separate issue for fixing each package?

@muthubentley I believe it's best if we have an issue per package. I filed [one for the property grid](https://github.com/iTwin/viewer-components-react/issues/676).

**Note:** We don't own all the mentioned packages, so we're only going to look into `tree-widget-react` and `property-grid-react`. Other teams will need to look into others (adding @aruniverse).

**Comment by muthubentley** [comment]
Thanks @grigasp
Created new issues  for @itwin/breakdown-trees-react and @itwin/measure-tools-react
https://github.com/iTwin/viewer-components-react/issues/677
https://github.com/iTwin/viewer-components-react/issues/678
