### ISSUE TITLE
@itwin/measure-tools-react bloated package size

### ISSUE THREAD

**Issue by linasburneika** [iTwin/viewer-components-react#732]
Published @itwin/measure-tools-react package contains `\lib\cjs\test\webpack` folder with test assets which weights 34.5Mb.
It's just taking space on disk and increase package restore time.

`\lib\cjs\test` and `\lib\esm\test` folders should be completed excluded from published package, these files are not needed to use the library

**Comment by aruniverse** [comment]
Would you like to contribute a fix for it? Should be very simple

**Comment by aruniverse** [comment]
please specify which version. this doesnt seem to be an issue with the latest releases

![image](https://github.com/iTwin/viewer-components-react/assets/11051042/550a142c-d19a-49fd-b8a7-ab4fc407783d)
