### ISSUE TITLE
Error in Property Grid when the browser tab is inactive for more than 10 minutes

### ISSUE THREAD

**Issue by muthubentley** [iTwin/viewer-components-react#736]
Issue:
Error in Property Grid when the browser tab is inactive for more than 10 minutes. Refer the below screenshot for error description:
![画像 (1)](https://github.com/iTwin/viewer-components-react/assets/107229931/9dc24537-2dfd-4428-8f54-6c8a22ccfca4)

Steps to reproduce:
Partner has developed a site with iTwin viewer. Issue is occurring in their website.
1) Open multiple tabs of iTwin viewer
2) Select an element in viewport and confirm that Property Grid pops up
3) Switch the tab and leave it as it is for around 10 to 15 minutes
4) Come back to the tab . Error occurs at this point.
5) Even if they press the retry button same error occurs again. If they refresh the browser then it comes back to normal

Not sure if it is related they could see the below API throwing 401
Request URL: https://api.bentley.com/imodel/rpc/v4/mode/1/context/850ef36a-18a0-4595-8fa7-9285d7276980/imodel/2064aefd-8bc6-4e0a-b670-374f87e023e0/changeset/12b84bed1ef6c6534ef0a65d11142fe00776a985/PresentationRpcInterface-4.0.0-getPagedContent
Response: {"statusCode": 401, "message": "Invalid JWT."}

Please investigate why this error is occurring and let us know if there are any workarounds.

**Comment by aruniverse** [comment]
As per the error message, the users access token expired and they need a new one

**Comment by muthubentley** [comment]
@aruniverse  I understand. Is the below explanation correct:
Normally when the tab is active this error doesnt occur. Which means there is a mechanism in place to refresh the expired token. But that mechanism will not work if the tab is inactive. 
2 questions on this:
1. Is there anyway to make this refresh token work when the user comes back to tab? I thought retry button was given for that purpose. But clicking that doesnt refresh the token so wanted to check if there is any other way.
2. Is it possible to extend the lifetime of user access token?

**Comment by grigasp** [comment]
> Is there anyway to make this refresh token work when the user comes back to tab? I thought retry button was given for that purpose. But clicking that doesnt refresh the token so wanted to check if there is any other way.

The "retry" button attempts to mount the component again, which in turn makes another request for properties. If the token is invalid, the second request fails too. Property grid by itself does absolutely nothing related to access tokens - it's acquired somewhere behind the scenes in itwinjs-core.

**Comment by muthubentley** [comment]
@grigasp  thanks for the explanation. retry button makes sense.
@aruniverse  can you confirm this:
Is the below explanation correct:
Normally when the tab is active this error doesnt occur. Which means there is a mechanism in place to refresh the expired token. But that mechanism will not work if the tab is inactive.
Questions:
1. Is there anyway to make this refresh token work when the user comes back to tab? 
2. Is it possible to extend the lifetime of user access token?

**Comment by aruniverse** [comment]
It is the responsibility of the Auth Client to refresh the token. If the tab is suspended then i guess its unable to do so, but it should be possible for you to add additional behavior to refresh the token (if needed) when your context switches back to the tab.

There is no way to extend the lifetime of an access token, you need to use the refresh token to get an updated access token

**Comment by muthubentley** [comment]
@aruniverse  Thanks for the explanation. Seems the problem is in Fukui's client side. Sorry for the trouble, closing the issue.
