### ISSUE TITLE
@itwin/map-layers has no direct or peer @itwin/itwinui-react dependency 

### ISSUE THREAD

**Issue by Juliakas** [iTwin/viewer-components-react#766]
### Version of the package
@itwin/map-layers@5.2.4 - same issue in master
### Version of iTwin.js used
iTwin.js Core packages: 4.3.3
AppUI: 4.9.0-dev.1 (with iTwinUI v3)
### What you expected to see, versus what you actually saw
File under `packages/itwin/map-layers/package.json` has no direct or peer @itwin/itwinui-react dependency even though itwinUI is used directly in your code for map-layers> This allows consumer app to @itwin/make map-layers use whatever iTwinUI version consumer app has installed.

In our case your package components were imported from iTwinUI v3 even though they are designed to work with iTwinUI v2. Peer dependency with specified version would have warned us (so we could override) OR direct dependency would completely solve it.

**Comment by GintV** [comment]
@mdastous-bentley Was this released yet?

**Comment by mdastous-bentley** [comment]
> @mdastous-bentley Was this released yet?

no not yet, should be soon.
