### ISSUE TITLE
Models Tree - Request performance improvement during visibility on/off with multi selection

### ISSUE THREAD

**Issue by muthubentley** [iTwin/viewer-components-react#797]
[Request from User]
Select multiple elements and turn visibility on/off – Elements visibility is turned on/off one by one with a little bit of delay. If possible please turn them on/off at once.
This can be reproduced in design review as well . Refer to the video in the below path:
https://bentley.sharepoint.com/:v:/r/sites/Fukui-BentleyCollaboration/Shared%20Documents/iTwin%20-%20CIMPHONY%20Plus/SampleData/TreePerformance/ModelTreeMultiSelection.mp4?csf=1&web=1&e=kxT1qn

**Comment by grigasp** [comment]
iModel: https://connect-imodelweb.bentley.com/imodeljs/?projectId=19c7abf7-77a6-4151-9ee9-f2fb9e2dfaab&iModelId=1395f52b-aba1-41e2-b8e1-8b9911c35807&ChangeSetId=0920ad2c63ad146b40740a64dadef427f2794c66

**Comment by grigasp** [comment]
I believe this has something to do with https://github.com/iTwin/viewer-components-react/pull/359, but needs further investigation.

**Comment by grigasp** [comment]
@muthubentley, [@itwin/tree-widget-react@2.1.0](https://www.npmjs.com/package/@itwin/tree-widget-react/v/2.1.0) with the fix is now released

**Comment by muthubentley** [comment]
Thank you
