### ISSUE TITLE
Tree displays zero items whenever the unit system changes

### ISSUE THREAD

**Issue by EK723** [iTwin/viewer-components-react#827]
When the unit system changes, the tree view displays zero items. The issue resolves itself after switching to a different type of tree (such as from Models to Categories). This error is occurring in @itwin/tree-widget-react v2.0.2

Step 1:
![Step 1](https://github.com/iTwin/viewer-components-react/assets/163031993/ab19bcad-da0d-4a68-8e4a-ed747e73b8fa)

Step 2:
![Step 2](https://github.com/iTwin/viewer-components-react/assets/163031993/70e3c36a-48d9-4c4c-b115-e230f5abe7b2)

Step 3:
![Step 3](https://github.com/iTwin/viewer-components-react/assets/163031993/2784d412-5f0e-4af3-8a9d-0bdc512a1956)

**Comment by saskliutas** [comment]
Issue was in `@itwin/presentation-components` package. Published `@itwin/presentation-components@5.2.2` with a fix,
