### ISSUE TITLE
Tree widget: Models Tree category visibility determined incorrectly in specific case

### ISSUE THREAD

**Issue by grigasp** [iTwin/viewer-components-react#913]
http://localhost:3000/?iTwinId=892aa2c9-5be8-4865-9f37-7d4c7e75ebbf&iModelId=f34cc831-7139-4419-b502-b165e4294ca3

https://bentley.sharepoint.com/:v:/s/Rules-DrivenPresentation/Eci4fI6ADNdBkbQYV8i8Lz0B9Jg9PJ5ZOOIHRQT_SmHzLw?e=FwYHNC

**Comment by Yato333** [comment]
The problem is that when some elements are in always/never drawn lists, category selector is ignored in determining visibility.
This is also somewhat related to #912 because models tree and categories tree use 2 different ways of determining visibility
