### ISSUE TITLE
Tree widget: Visibility of parent nodes isn't updated when children' visibility is changed quickly

### ISSUE THREAD

**Issue by grigasp** [iTwin/viewer-components-react#922]
http://localhost:3000/?iTwinId=b391ba44-add7-47a0-8375-f2889a3540e8&iModelId=ba504f88-a479-4156-9d81-658ee169588e

![Image](https://github.com/iTwin/viewer-components-react/assets/35135765/e3313849-6b70-4978-8a12-f7f811585d27)

Setting network throttling to "Slow 3G" in Chrome DevTools helps to reproduce this.

**Comment by Yato333** [comment]
The problem is not related to how quickly visibility changes.
If you click on the "Weld" grouping node, category visibility always get's partial instead of visible
