### ISSUE TITLE
PropertyGrid shows an error when selecting a 2D element of a sheet view

### ISSUE THREAD

**Issue by thanhbinh-d** [iTwin/viewer-components-react#929]
Steps to reproduce:

- On Pineapple, open the Main frontstage, then open a sheet.
- On the sheer view, select a 2D element.
- Observe that there is an error (Error - An error occurred while loading properties.) shown on top of the property grid widget.

The imodel used for testing can be provided.
Version:

- AppUI: 4.13.3
- @itwin/presentation-components: 5.3.4
- @itwin/tree-widget-react: 2.3.1

Please refer to the below screenshots for more info:
![Screenshot 2024-06-10 at 10 41 22 AM](https://github.com/iTwin/viewer-components-react/assets/169864714/351122cc-1b6b-43aa-b89a-50721dc11b50)
![Screenshot 2024-06-10 at 11 52 10 AM](https://github.com/iTwin/viewer-components-react/assets/169864714/87afb0c9-bbee-4b78-ac2f-ee8660bc3adf)
![Screenshot 2024-06-10 at 11 54 46 AM](https://github.com/iTwin/viewer-components-react/assets/169864714/c5f611aa-dc24-45c5-8251-8e9daeeb819d)

**Comment by grigasp** [comment]
@thanhbinh-d, FYI, the fix has been released with `itwinjs-core@4.7.2` and deployed to GPB (currently only dev and qa).

**Comment by thanhbinh-d** [comment]
@grigasp , I've tested on QA and confirmed the issue was fixed. E.g. the properties were shown on the widget without error.
![Screenshot 2024-06-25 at 3 55 50 PM](https://github.com/iTwin/viewer-components-react/assets/169864714/0f25ca6a-f424-4449-9b95-6b4646f1b36a)
